import {dateKey,monday,addDays,categories,statuses} from '../core/model.js';
import {esc,button,empty} from '../components/ui.js';
export function calendar(data,ui){
 const week=monday(ui.date),month=ui.date.slice(0,7),start=ui.mode==='month'?monday(month+'-01'):week;
 const days=Array.from({length:ui.mode==='month'?42:7},(_,i)=>addDays(start,i));
 const visible=data.events.filter(e=>(!ui.filter||e.subjectId===ui.filter)&&(!ui.query||`${e.title} ${e.detail} ${data.subjects.find(s=>s.id===e.subjectId)?.name}`.toLowerCase().includes(ui.query.toLowerCase())));
 const title=ui.mode==='month'?new Date(ui.date+'T12:00').toLocaleDateString('vi-VN',{month:'long',year:'numeric'}):`${new Date(week+'T12:00').toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit'})} — ${new Date(addDays(week,6)+'T12:00').toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'})}`;
 return `<div class="page-heading"><div><p class="eyebrow">SẮP XẾP THỜI GIAN CỦA BẠN</p><h1>Lịch học</h1></div>${button('+ Thêm buổi học','new-event','primary')}</div>
 <section class="stats"><div><span>Buổi học trong tuần</span><strong>${data.events.filter(e=>e.date>=week&&e.date<=addDays(week,6)).length}<small>buổi</small></strong></div><div><span>Đã hoàn thành trong tuần</span><strong>${data.events.filter(e=>e.date>=week&&e.date<=addDays(week,6)&&e.status==='done').length}<small>buổi</small></strong></div><div><span>Môn đang theo dõi</span><strong>${data.subjects.length}<small>môn học</small></strong></div></section>
 <section class="calendar-panel"><div class="calendar-toolbar"><div class="date-controls">${button('‹','prev','icon','aria-label="Khoảng thời gian trước"')}<h2>${title}</h2>${button('›','next','icon','aria-label="Khoảng thời gian sau"')}${button('Hôm nay','today')}</div><div class="segmented">${button('Tuần','week',ui.mode==='week'?'selected':'')}${button('Tháng','month',ui.mode==='month'?'selected':'')}</div></div>
 <div class="filters"><label class="search-label">Tìm lịch<input id="search" placeholder="Tên buổi học, môn học…" value="${esc(ui.query)}"></label><label>Môn học<select id="subject-filter"><option value="">Tất cả môn học</option>${data.subjects.map(s=>`<option value="${esc(s.id)}" ${ui.filter===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><div class="legend">${Object.entries(categories).map(([,c])=>`<span><i style="background:${c.color}"></i>${c.label}</span>`).join('')}</div></div>
 <div class="calendar-scroll"><div class="calendar-grid ${ui.mode}">${days.map(day=>{const date=new Date(day+'T12:00'),today=day===dateKey(),events=visible.filter(e=>e.date===day).sort((a,b)=>a.start.localeCompare(b.start));return `<section class="day ${today?'today':''} ${ui.mode==='month'&&!day.startsWith(month)?'muted-day':''}"><header><span>${['CN','Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7'][date.getDay()]}</span><b>${date.getDate()}</b>${button('+','new-event','day-add',`data-date="${day}" aria-label="Thêm buổi học ngày ${day}"`)}</header><div class="day-events">${events.map(e=>{const s=data.subjects.find(s=>s.id===e.subjectId),c=categories[s.category];return `<button class="event ${e.status==='done'?'completed':''}" style="--color:${c.color};--tint:${c.bg}" data-action="edit-event" data-id="${esc(e.id)}"><span class="event-time">${e.start} – ${e.end}</span><strong>${esc(e.title)}</strong><span>${esc(s.name)}</span>${ui.mode==='week'?`<small>${esc(e.location||'Chưa đặt địa điểm')}</small>`:''}<em>${statuses[e.status]}</em></button>`;}).join('')}${!events.length&&ui.mode==='week'?'<p class="free-day">Chưa có lịch</p>':''}</div></section>`;}).join('')}</div></div>
 <footer class="calendar-footer"><span>Chọn một buổi học để xem chi tiết, sửa hoặc đánh dấu hoàn thành.</span><span>Lịch theo giờ địa phương</span></footer></section>${!data.subjects.length?empty('Bắt đầu bằng môn học đầu tiên, hoặc nạp dữ liệu minh họa ở phần Dữ liệu.','new-subject','+ Tạo môn học'):''}`;
}
